---
title: "Detecting Idiographic Personality Change"
author: "Emorie D Beck"
institution: "Washington University in St. Louis"
date: "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"
output:
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Workspace
```{r}
packages <- c("psych", "parallel", "plyr", "tidyverse")
new.packages <- packages[!(packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

if(!("results" %in% list.files())){dir.create("~/results")}

library(psych)
library(parallel)
library(plyr)
library(tidyverse)
wd <- "~/Documents/Github/KCP"
read.path <- "https://github.com/emoriebeck/KCP"
write.path <- "~/"
# write.path <- wd
```

## Packages

## Functions

## Data

### Create a codebook
```{r}
Big5 <- c("Extraversion", "Agreeableness", "Conscientiousness", "Neuroticism", "Openness")
codebook <- crossing(
  inventory = "tipi",
  traittmp = c("e", "a", "c", "n", "o"),
  week = c(paste("0",1:9, sep = ""), 10:60)
) %>%
  mutate(trait = mapvalues(traittmp, c("e", "a", "c", "n", "o"), Big5),
         type = "personality") %>%
  unite(item, inventory, traittmp, week, sep = "") %>%
full_join(
crossing(
  tmp = "relevents",
  num = c(paste("0", c(3,4,6,8,9), sep = ""), "10", "11")
) %>%
  mutate(trait = mapvalues(num, unique(num), c("famPassed", "partTrav", "pregnant", 
                            "engaged", "moveIn", "married", "brokeUp")),
         type = "event") %>%
  unite(item, tmp, num, sep = "")
)
```


### Load the data
```{r, eval = F}
# CREATE A COEBOOK
weekly <- url(sprintf("%s/blob/master/data/Longitudinal_Weekly_1_Year/metaresearch2-corrected-web.sav?raw=true", read.path)) %>%
  haven::read_sav()

weekly_long <- weekly %>%
  select(ID, contains("tipi"), contains("relevents")) %>%
  gather(key = item, value = value, -ID, na.rm = T) %>%
  full_join(codebook) %>%
  mutate(week = as.numeric(str_remove_all(item, "[a-z]"))) %>%
  select(-item) %>% 
  filter(value != 0) %>%
  arrange(ID, trait, type, week) 

weekly_wide <- weekly_long %>% 
  filter(type == "personality") %>%
  spread(key = trait, value = value) %>%
  select(-type)

save(weekly_long, weekly_wide, file = sprintf("%s/data/data.RData", write.path))
```

# KCP 
```{r}
source(sprintf('%s/blob/master/scripts/functions.R?raw=true', read.path))
load(url(sprintf('%s/blob/master/data/data.RData?raw=true', read.path)))
start <- Sys.time()

KCP_nested <- weekly_wide %>% 
  group_by(ID) %>%
  mutate(n = n()) %>%
  filter(n > 25) %>%
  select(-n) %>%
  arrange(ID, week) %>%
  nest() 

subs <- unique(KCP_nested$ID)

KCP_nested <- KCP_nested %>%  
  filter(ID %in% subs[1:10]) %>%
  mutate(KCP = map2(data, ID, ~KCP(
    data = .x       # N x P numeric matrix or data frame
  , kmax = 3        # max number of change points to test
  , window = 10     # the size of the moving window used for correlations
  , timevar = "week"# name of the time variable for sorting
  , iter = 1000     # number of permutations
  , alpha = .05     # "significance criterion"
  , rule = "OR"     # should both variance and variance drop tests be required to be significant
  , perm_path = sprintf("%s/results/perm_data", write.path) # path to save the permuted data sets and moving window correlations to
  , vhat_path = sprintf("%s/results/vhats", write.path) # path to save the v hat values, if desired
  , out_path = sprintf("%s/results/out", write.path) # path to save the v hat values, if desired
  , ID = .y  
  )))
end <- Sys.time()
print(paste("Time elapsed", round(end-start,2)))


KCP_nested <- KCP_nested %>%
  mutate(
    v_test = map_dbl(KCP, ~.$v_test)
    , v_drop = map(KCP, ~.$v_drop)
    , cp = map_chr(KCP, ~.$cp)
  )

KCP_nested %>%
  group_by(cp) %>%
  summarize(n = n())

KCP_nested %>%
  filter(cp == "CP") %>%
  select(-v_test, -cp) %>%
  unnest(v_drop) %>% 
  filter(k > 0) %>%
  group_by(ID) %>%
  filter(p == min(p, na.rm = T))

(KCP_nested %>%
  filter(cp == "CP"))$KCP[[1]]$r_hats_perm
(KCP_nested %>%
  filter(cp == "CP"))$KCP[[1]]$r_hats

```

# Ancillary Figures for SPSP Presentation  

## Time Series Visualization  
```{r}
ex_dat <- weekly_wide %>% 
  filter(ID == "204")

ex_dat_long <- ex_dat %>%
  gather(key = Trait, value = value, -ID, -week) 

ex_dat_long %>%
  mutate(xmin = 25, xmax = 35, ymin = 1, ymax = 7) %>%
  mutate(shrt_trait = mapvalues(Trait, Big5, c("E", "A", "C", "N", "O"))) %>%
  ggplot(aes(x = week, y = value, color = shrt_trait)) +
  scale_y_continuous(limits = c(1,7), breaks = seq(1,7,2)) + 
  scale_x_continuous(limits = c(1,55), breaks = seq(1,55,5)) + 
    geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      fill = "khaki1", alpha = .5, color = "white") +
  geom_line() + 
  labs(x = "Week", y = "Rating (1-7)") +
  facet_wrap(~shrt_trait, nrow = 5, strip.position = "right") + 
  theme_classic() + 
  theme(legend.position = "none",
        strip.text = element_text(face = "bold", angle = 0, size = rel(2)),
        axis.text = element_text(face = "bold"),
        axis.title = element_text(face = "bold", size = rel(1.2)))
ggsave(sprintf("%s/results/pres_figs/time_series_ex.png", write.path),
       width = 8, height = 5)
```

## Moving Window Visualization
```{r}
mw_plot_fun <- function(i){
  ex_dat_long %>%
  mutate(xmin = i-5, xmax = i+4, ymin = 1, ymax = 7) %>%
  mutate(shrt_trait = mapvalues(Trait, Big5, c("E", "A", "C", "N", "O"))) %>%
  ggplot(aes(x = week, y = value, color = shrt_trait)) +
  scale_y_continuous(limits = c(1,7), breaks = seq(1,7,2)) + 
  scale_x_continuous(limits = c(1,55), breaks = seq(1,55,5)) + 
    geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      fill = "khaki1", alpha = .5, color = "white") +
  geom_line() + 
  labs(x = "Week", y = "Rating (1-7)") +
  facet_wrap(~shrt_trait, nrow = 5, strip.position = "right") + 
  theme_classic() + 
  theme(legend.position = "none",
        strip.text = element_text(face = "bold", angle = 0, size = rel(2)),
        axis.text = element_text(face = "bold"),
        axis.title = element_text(face = "bold", size = rel(1.2)))
}

library(animation)
#set up function to loop through the draw.a.plot() function
loop.animate <- function() {
  lapply(6:50, function(i) {
    print(mw_plot_fun(i))
  })
}

saveGIF(loop.animate(), interval = .25, movie.name="mw_timeseries.gif", ani.width = 800, ani.height = 500)

ex_dat_long %>%
  mutate(xmin = 1, xmax = 10, ymin = 1, ymax = 7) %>%
  mutate(shrt_trait = mapvalues(Trait, Big5, c("E", "A", "C", "N", "O"))) %>%
  ggplot(aes(x = week, y = value, color = shrt_trait)) +
  scale_y_continuous(limits = c(1,7), breaks = seq(1,7,2)) + 
  scale_x_continuous(limits = c(1,55), breaks = seq(1,55,5)) + 
    geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      fill = "khaki1", alpha = .5, color = "white") +
  geom_line() + 
  labs(x = "Week", y = "Rating (1-7)") +
  facet_wrap(~shrt_trait, nrow = 5, strip.position = "right") + 
  theme_classic() + 
  theme(legend.position = "none",
        strip.text = element_text(face = "bold", angle = 0, size = rel(2)),
        axis.text = element_text(face = "bold"),
        axis.title = element_text(face = "bold", size = rel(1.2)))
ggsave(sprintf("%s/results/pres_figs/mw_timeseries.png", write.path),
       width = 8, height = 5)

mw_cor <- mw_cor_fun(ex_dat %>% select(-ID, -week), window = 10) %>%
  mutate(V1 = mapvalues(V1, Big5, c("E", "A", "C", "N", "O")),
         V2 = mapvalues(V2, Big5, c("E", "A", "C", "N", "O"))) %>%
  unite(tmp, V1, V2, sep = "-") 

gausssim_plot_fun <- function(x,y){
  mw_cor %>%
  mutate(xmin1 = x, xmax1 = x, ymin = -1, ymax = 1,
         xmin2 = y, xmax2 = y) %>%
    ggplot(aes(x = i, y = r, color = tmp)) +
      scale_y_continuous(limits = c(-1.1,1.1), breaks = seq(-1,1,1)) +
      scale_x_continuous(limits = c(1,55), breaks = c(1,seq(5,55,5))) +
      # geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      #   fill = "khaki1", alpha = .5, color = "white") +
      geom_line() + 
      geom_point(data = . %>% filter(i == x), size = 4) +
      geom_point(data = . %>% filter(i == y), size = 4) +
      geom_text(data = . %>% filter(i == x), aes(label = round(r, 1), y = ifelse(r > 0, r - .6, r + .6))) +
      geom_text(data = . %>% filter(i == y), aes(label = round(r, 1), y = ifelse(r > 0, r - .6, r + .6))) +
      labs(x = "Week", y = "Moving window Correlation") +
      facet_wrap(~tmp, ncol = 1, strip.position = "right") + 
      theme_classic() + 
      theme(legend.position = "none",
            strip.text = element_text(face = "bold", angle = 0, size = rel(1.3)),
            axis.text = element_text(face = "bold"),
            axis.title = element_text(face = "bold", size = rel(1.2)))
}

loop.animate <- function() {
  lapply(6:8, function(i) {
    lapply((i+1):50, function(k){
      print(gausssim_plot_fun(i,k))
    })
  })
}

saveGIF(loop.animate(), interval = .1, movie.name="gaussim_series.gif", ani.width = 800, ani.height = 500)

mw_cor %>%
  mutate(xmin = 25, xmax = 35, ymin = -1, ymax = 1) %>%
  ggplot(aes(x = i, y = r, color = tmp)) +
    scale_y_continuous(limits = c(-1,1), breaks = seq(-1,1,1)) +
    scale_x_continuous(limits = c(1,55), breaks = c(1,seq(5,55,5))) +
    geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      fill = "khaki1", alpha = .5, color = "white") +
    geom_line() + 
    labs(x = "Week", y = "Moving window Correlation") +
    facet_wrap(~tmp, ncol = 1, strip.position = "right") + 
    theme_classic() + 
    theme(legend.position = "none",
          strip.text = element_text(face = "bold", angle = 0, size = rel(1.3)),
          axis.text = element_text(face = "bold"),
          axis.title = element_text(face = "bold", size = rel(1.2)))
ggsave(sprintf("%s/results/pres_figs/mwr_series_ex.png", write.path),
       width = 8, height = 5)
```


## Gaussian Similarity  
```{r}
mwr_plot_fun <- function(x){
  mw_cor %>%
  mutate(xmin = x-1, xmax = x+1, ymin = -1, ymax = 1) %>%
    ggplot(aes(x = i, y = r, color = tmp)) +
      scale_y_continuous(limits = c(-1.1,1.1), breaks = seq(-1,1,1)) +
      scale_x_continuous(limits = c(1,55), breaks = c(1,seq(5,55,5))) +
      # geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      #   fill = "khaki1", alpha = .5, color = "white") +
      geom_line() + 
      geom_point(data = . %>% filter(i == x), size = 4) +
      geom_text(data = . %>% filter(i == x), aes(label = round(r, 1), y = ifelse(r > 0, r - .6, r + .6))) +
      labs(x = "Week", y = "Moving window Correlation") +
      facet_wrap(~tmp, ncol = 1, strip.position = "right") + 
      theme_classic() + 
      theme(legend.position = "none",
            strip.text = element_text(face = "bold", angle = 0, size = rel(1.3)),
            axis.text = element_text(face = "bold"),
            axis.title = element_text(face = "bold", size = rel(1.2)))
}

loop.animate <- function() {
  lapply(6:50, function(i) {
    print(mwr_plot_fun(i))
  })
}

saveGIF(loop.animate(), interval = .25, movie.name="mwr_series.gif", ani.width = 800, ani.height = 500)

```

## Within-Phase Variance
```{r}
mw_cor %>%
  mutate(xmin2 = 25, xmax2 = 35, ymin = -1, ymax = 1,
         xmin1 = 6, xmax1 = 24, xmin3 = 36, xmax3 = 50) %>%
  ggplot(aes(x = i, y = r, color = tmp)) +
    scale_y_continuous(limits = c(-1,1), breaks = seq(-1,1,1)) +
    scale_x_continuous(limits = c(1,55), breaks = c(1,seq(5,55,5))) +
    geom_rect(aes(xmin = xmin2, xmax = xmax2, ymin = ymin, ymax = ymax),
      fill = "khaki1", alpha = .5, color = "khaki1") +
    geom_rect(aes(xmin = xmin1, xmax = xmax1, ymin = ymin, ymax = ymax),
      fill = "white", alpha = 0, color = "gray") +
    geom_rect(aes(xmin = xmin3, xmax = xmax3, ymin = ymin, ymax = ymax),
      fill = "white", alpha = 0, color = "gray") +
    geom_line() + 
    labs(x = "Week", y = "Moving window Correlation") +
    facet_wrap(~tmp, ncol = 1, strip.position = "right") + 
    theme_classic() + 
    theme(legend.position = "none",
          strip.text = element_text(face = "bold", angle = 0, size = rel(1.3)),
          axis.text = element_text(face = "bold"),
          axis.title = element_text(face = "bold", size = rel(1.2)))
ggsave(sprintf("%s/results/pres_figs/mwr_series_ex_k2.png", write.path),
       width = 8, height = 5)

tau_p <- 35
tau_p_min_1 <- 25
R <- mw_cor %>% group_by(i) %>% select(-tmp) %>% nest()
inner <- crossing(inner_l = (tau_p_min_1+1):tau_p,
                    outer_l = (tau_p_min_1+1):tau_p) %>%
    filter(inner_l != outer_l & inner_l < outer_l) %>%
    left_join(R %>% dplyr::select(inner_l = i, R_i = data)) %>%
    left_join(R %>% dplyr::select(outer_l = i, R_j = data)) %>%
    mutate(inner = map2_dbl(R_i, R_j, possibly(gauss_kernal_fun, NA_real_)))

gausssim_short_plot_fun <- function(R_i, R_j, G_k){
  tmp <- tibble(r = .8, tmp = "C-A", i = 48, G = ifelse(G_k < .1, sprintf("%.1e", G_k), sprintf("%.1f", G_k)))
  mw_cor %>%
    ggplot(aes(x = i, y = r, color = tmp)) +
      scale_y_continuous(limits = c(-1.1,1.1), breaks = seq(-1,1,1)) +
      scale_x_continuous(limits = c(1,55), breaks = c(1,seq(5,55,5))) +
      # geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      #   fill = "khaki1", alpha = .5, color = "white") +
      geom_line() + 
      geom_point(data = . %>% filter(i == R_i), size = 4) +
      geom_point(data = . %>% filter(i == R_j), size = 4) +
      geom_text(data = . %>% filter(i == R_i), aes(label = round(r, 1), y = ifelse(r > 0, r - .6, r + .6))) +
      geom_text(data = . %>% filter(i == R_j), aes(label = round(r, 1), y = ifelse(r > 0, r - .6, r + .6))) +
      geom_label(data = tmp, aes(label = G), color = "black") + 
      # annotate("text", x = 55, y = 1, label = round(G_k,1)) + 
      labs(x = "Week", y = "Moving window Correlation") +
      facet_wrap(~tmp, ncol = 1, strip.position = "right") + 
      theme_classic() + 
      theme(legend.position = "none",
            strip.text = element_text(face = "bold", angle = 0, size = rel(1.3)),
            axis.text = element_text(face = "bold"),
            axis.title = element_text(face = "bold", size = rel(1.2)))
}

loop.animate <- function() {
  lapply(1:nrow(inner), function(i){
    print(gausssim_short_plot_fun(inner$inner_l[i], inner$outer_l[i], inner$inner[i]))
})
}

saveGIF(loop.animate(), interval = .1, movie.name="gaussim_series_short.gif", ani.width = 800, ani.height = 500)
```


